name: Keep-Alive Service

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:  # Manual trigger for testing

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Run keep-alive
      run: node keep-alive.js
      env:
  SERVER_URL: https://colyseus-3d-demo-9yuv.onrender.com
